CONFIG = {
    'dir_path':"G:/无源感知研究/数据采集/2019_07_18/",
    'data_name': "实验室(2t3r)(resample)(归一化).mat",
    'source_name': "实验室(2t3r)(resample)(归一化).mat",
    'target_name': "会议室(2t3r)(resample)(归一化).mat",
    'num_workers': 4,
    'pin_memory': True,
    'batch_size': 32,
    'epochs': 1000,
    'log_interval':1,
    'lr': 1e-3,
    'momentum': .9,
    'l2_decay': 0.01,
    'lambda': 10,
    'sequence_max_len': 750,
    'input_feature': 180,
    # 'sequence_max_len': 677,
    # 'input_feature': 270,
    'hidden_size': 300,
    'n_class': 6,
    'model_type':'conv1d',
    'model_save_path': 'model_conv.pkl',
    'tensorboard_log_path': 'tensorboard_log/DAN_conv1d_lab_to_meeting_adam_source_test_2',
    'diff_lr':True,
    'gamma':1
}
